services:
  backend:
    build: .
    container_name: mesa_ayuda_backend
    env_file:
      - .env
    volumes:
      - /var/log/mesa_ayuda:/app/logs
    ports:
      - "100.83.75.109:8105:8105"
    restart: unless-stopped
